# Generated by Django 2.0.6 on 2018-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(default=0, upload_to='static/uploads', verbose_name='image'),
            preserve_default=False,
        ),
    ]
